services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  game_engine:
    build: ./game_engine
    ports:
      - "8888:8888"
    volumes:
      - ./game_engine:/code
    depends_on:
      - backend

  player_client:
    build: ./player_client
    ports:
      - "3000:3000"
    volumes:
      - ./player_client:/app
    depends_on:
      - backend
      - game_engine
